### ISSUE TITLE
Thanks for your work!

### ISSUE THREAD

**Issue by fat0troll** [rauenzi/ModernRenai#1]
In recent events, renai forum had to migrate to the new server, and in a process we found your theme and ported it to phpbb directly, so forums now have proper looks out of the box.

So here I want to say thank you for your work that made this possible.

We have now modernrenai theme as phpbb theme code here: https://codeberg.org/fhs/modern-renai. You can contribute, if you want.

**Comment by zerebos** [comment]
Oh wow that's really awesome, I'm glad to see this become the new default for the forum! I'll definitely be sure to contribute if I find anything that needs adjusting or fixing.

**Comment by zerebos** [comment]
I was going to archive this but I think I may keep this around for the alternate style it offers as well as tweaks for widescreens. I don't believe phpbb has a way for themes to allow user customization like that.

**Comment by fat0troll** [comment]
phpbb doesn't have such customization, as far as I aware of :(

**Comment by fat0troll** [comment]
also, I consider porting Modern style too, as optional theme for users to enable on forums directly, if you don't mind

**Comment by zerebos** [comment]
> phpbb doesn't have such customization, as far as I aware of :(

Yeah it doesn't :/ part of why I stopped using it for my forums a long time ago tbh

> I consider porting Modern style too, as optional theme for users to enable on forums directly, if you don't mind

I definitely wouldn't mind, but I'll leave that up to you! I can even help out if you want. Should we open this as a feature req on codeberg?

**Comment by fat0troll** [comment]
actually, it may be useful!

we have created custom dark mode for the theme (called Chocolate), so you will have an example how to add custom theme

also, we have some kind of user interface now to manage theme props, so you may investigate it around and see if you can port all other options of ModernRenai to forum theme (eg, width selection and custom accent color)

**Comment by fat0troll** [comment]
well, custom user interface idea for themes is kinda non worked, but everything else from my previous comment is correct :)

**Comment by zerebos** [comment]
Awesome, glad to hear it! I might take a look when I free up some time!
